apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  type: ClusterIP
  selector:
    app: config
  ports:
  - port: 8071
    targetPort: 8071
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
spec:
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: config
        image: koedakyokotsu/config-server:latest
#        resources:
#          requests:
#            memory: "32Mi"
#            cpu: "100m"
#          limits:
#            memory: "128Mi"
#            cpu: "500m"
        ports:
        - containerPort: 8071


