apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  type: ClusterIP
  selector:
    app: eureka-server
  ports:
  - port: 8761
    targetPort: 8761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
spec:
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: koedakyokotsu/eureka-server:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: kube
        ports:
        - containerPort: 8761
