apiVersion: v1
kind: Service
metadata:
  name: event-analysis
spec:
  type: ClusterIP
  selector:
    app: event-analysis
  ports:
  - port: 8085
    targetPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-analysis-deployment
spec:
  selector:
    matchLabels:
      app: event-analysis
  template:
    metadata:
      labels:
        app: event-analysis
    spec:
      containers:
      - name: event-analysis
        image: koedakyokotsu/event-analysing-service:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: kube
          - name: MONGODB_URI
            value: "mongodb://mongodb-service:27017/event-analysis?authSource=admin"
          - name: KAFKA_BROKER
            value: kafka-service.default.svc.cluster.local:9092
        ports:
        - containerPort: 8085

