apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongodb-pc-volume-claim
      containers:
        - name: mongodb
          image: mongo
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/data/db"
              name: mongodb
      restartPolicy: Always
  selector:
    matchLabels:
      app: mongodb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pc-volume
  labels:
    type: local
    app: mongodb
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pc-volume-claim
  labels:
    app: mongodb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
