apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  type: ClusterIP
  selector:
    app: notifications
  ports:
  - port: 8088
    targetPort: 8088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-deployment
spec:
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - name: notifications
        image: koedakyokotsu/notification-service
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: kube
        ports:
        - containerPort: 8088

