apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
  - port: 8082
    targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: koedakyokotsu/order-service:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: kube
          - name: MONGODB_URI
            value: "mongodb://mongodb-service:27017/orders?authSource=admin"
          - name: KAFKA_BROKER
            value: kafka-service.default.svc.cluster.local:9092
        ports:
        - containerPort: 8082


