apiVersion: v1
kind: Service
metadata:
  name: tickets-service
spec:
  type: ClusterIP
  selector:
    app: tickets
  ports:
  - port: 8081
    targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-deployment
spec:
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
      - name: tickets
        image: koedakyokotsu/ticketing-service:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: kube
          - name: MONGODB_URI
            value: "mongodb://mongodb-service:27017/tickets?authSource=admin"

        ports:
        - containerPort: 8081

