spring:
  application:
    name: eurekaServer
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8071
management:
  endpoints:
    web:
      exposure:
        include: '*'



