#spring:
#  application:
#    name: users
#  profiles:
#    active: dev
#  config:
#    import: configserver:http://localhost:8071
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"