spring:
  application:
    name: configServer
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yohannes-teshale/event-ticketing-microservice-configuration-server.git
          clone-on-start: true
          default-label: main

server:
  port: 8071
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
